name: SCA - Fast Dependency Review

on:
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high
          comment-summary-in-pr: true
          deny-licenses: |
            GPL-3.0
            AGPL-3.0
            LGPL-3.0
