name: Semgrep Code Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  semgrep:
    runs-on: ubuntu-latest
    name: Run Semgrep scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: auto
